spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/querydsl
    driver-class-name: org.h2.Driver
    username: sa
    password: 1234

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 200
        show_sql: true
  data:
    web:
      pageable:
        max-page-size: 2000
        default-page-size: 10
logging:
  level:
    org.hibernate.sql: debug
